auto: true
markdown: rdiscount
exclude: ["README.md"]

baseurl:      /smeadaptation.org
title: "SME Adaptation"
author:    "Global Adaptation Institute - Tecnológico de Monterrey"
description:    "SME Adaptation website to support our Templeton grant."
keywords: "climate, adaptation, sme"
root_desc:      "SMEadaptation"


rdiscount extensions: [smart]
